### ISSUE TITLE
array_walk() expects parameter 1 to be array, null given

### ISSUE THREAD

**Issue by RThorne** [AliHichem/AliDatatableBundle#121] opened 2015-07-22 17:06 UTC
This happens on dev environment whenever I log out from my application and persists on all pages. The only way to get out of this, is to include Datatable in the login form. Then the page can be loaded and Datatable can be deleted. After that I can navigate wherever I want and even login.
It doesn't happen again until I log out.

This only happens on dev environment and I wasn't able to reproduce it in prod.

My suspicion is that this has something to do with session data.

Top of the stacktrace:
in vendor/ali/datatable/Ali/DatatableBundle/EventListener/DatatableListener.php at line 73

![image](https://cloud.githubusercontent.com/assets/2671730/8831759/2737196e-30ad-11e5-954d-dddec0d33aa8.png)

**Comment by JoseFanjul** [comment] 2015-07-23 06:48
Yesterday I worked perfectly and today shows me the same problem.

**Comment by kuldipem** [comment] 2015-07-23 12:49
I also got many time, but now it is working fine.

**Comment by AliHichem** [comment] 2015-07-23 12:58
Thank you guys for letting me know about this,  what version of symfony are you using ?

**Comment by kuldipem** [comment] 2015-07-23 13:00
I have created a  pull request #123 ,  to fix issue.  I am using SF 2.7.

**Comment by AliHichem** [comment] 2015-07-23 13:09
hey kuldipem, I just replied to your pull request : I've rejected it because of the short array syntax. If you like I can wait for you to fix that

**Comment by RThorne** [comment] 2015-07-23 13:17
I am using SF 2.7.2

**Comment by AliHichem** [comment] 2015-07-23 13:21
@RThorne I'm using the same version as both of you and @kuldipem  but I don't reproduce the problem. @kuldipem just pushed a fix that I accepted, would you mind updating your datatable bundle and check if works well ?

**Comment by JoseFanjul** [comment] 2015-07-23 13:21
Me too use 2.7.2. I only put false the dev mode, and when back true works fine ??.

**Comment by RThorne** [comment] 2015-07-23 13:33
Looks like it is working now, I wasn't able to reproduce the error again. Thanks for the fix @kuldipem

**Closed** 2015-07-24 08:43 UTC
